{{- if .Values.certificates.create }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "fullname" . }}-client.{{ .Values.certificates.domain }}
  annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  secretName: client.{{ .Values.certificates.domain }}
  commonName: client.{{ .Values.certificates.domain }}
  issuerRef:
    name: ca.{{ .Values.certificates.domain }}
    kind: Issuer
{{- end }}
