{{- if .Values.gvmd.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-gvmd-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.gvmd.secrets }}
{{ $key | quote | indent 2 }}: {{ tpl ($value | toString) $ | quote }}
{{- end }}
{{- end }}
