{{- if .Values.ospd_openvas.syncNvtData.cronjob.enabled }}
{{- if .Values.ospd_openvas.syncNvtData.cronjob.createServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-ospd-openvas-service-account
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fullname" . }}-ospd-openvas-exec-role
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}-ospd-openvas-exec-role-binding
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-ospd-openvas-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-ospd-openvas-exec-role
{{- end }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gvm-ospd-openvas-sync-nvt-data
  namespace: security
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gvm-service-account
          automountServiceAccountToken: true
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            args:
              - exec
              - -it
              - -n
              - security
              - gvm-ospd-openvas-0
              - -c
              - ospd-openvas
              - --
              - /bin/bash 
              - -c 
              - "/sync-greenbone-nvt-data.sh --resync"
          restartPolicy: Never
{{- end }}
