{{- if .Values.ospd_openvas.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-ospd-openvas-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.ospd_openvas.secrets }}
{{ $key | quote | indent 2 }}: {{ tpl ($value | toString) $ | quote }}
{{- end }}
{{- end }}
